

services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

  api:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - JWT_SECRET=your-secret-key-here
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app?schema=public
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./prisma:/app/prisma
    working_dir: /app
    depends_on:
      - db

volumes:
  dbdata: