services:

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

  api:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db

volumes:
  dbdata:
